#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/vscode/bin/linux-x64/ddc367ed5c8936efe395cffeec279b04ffd7db78/node" "/home/vscode/.vscode-remote/data/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "code --openExternal " "$@"